# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FrontApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FrontApp
  #pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'GoogleMaps'

  target 'FrontApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FrontAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FrontApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FrontApp-tvOS

end
